matrix:
  platform:
    - linux/amd64
    - linux/arm64
    - linux/riscv64

steps:
  test:
    image: gitea.elara.ws/elara6331/golang:latest
    commands:
      - go test
    when:
      - event: push
